### ISSUE TITLE
run gcr-cleaner-cli as CronJob on GKE 

### ISSUE THREAD

**Issue by xpicio** [sethvargo/gcr-cleaner#47]
Hello, i'm trying to run gcr-cleaner-cli as CronJob on GKE (version 1.19.13-gke.701) with workload identity enabled, but i have an issue with the authentication on artifact registry hosted on GCP.

The configuration step that i did to allow the pod to handle the artifact registry are the following:

1. create a service account on GCP named gcr-cleaner-gcp
1.a associate to this service account the role roles/artifactregistry.repoAdmin
1.b associate to this service account the workload identity binded with a ServiceAccount create in the cluster (gcr-cleaner-cluster) with role roles/iam.workloadIdentityUser
2. create a ServiceAccount in the cluster named gcr-cleaner-cluster
3. create a CronJob running with serviceAccountName: gcr-cleaner-cluster

Maybe the terraform step and the k8s yaml are easiest to understand:

Terraform:
````
resource "google_service_account" "gcr_cleaner" {
  account_id   = "gcr-cleaner"
  display_name = "GCR Cleaner Account"
}

resource "google_artifact_registry_repository_iam_binding" "artifact_registry_admin" {
  provider = google-beta

  depends_on = [
    google_service_account.gcr_cleaner
  ]

  project    = data.google_client_config.current.project
  location   = data.google_client_config.current.region
  repository = "container-registry"

  role = "roles/artifactregistry.repoAdmin"

  members = [
    "serviceAccount:${google_service_account.gcr_cleaner.email}"
  ]
}

resource "google_service_account_iam_binding" "service_account_workload_indentity" {
  depends_on = [
    google_service_account.gcr_cleaner
  ]

  service_account_id = google_service_account.gcr_cleaner.name
  role               = "roles/iam.workloadIdentityUser"

  members = [
    "serviceAccount:project-id.svc.id.goog[default/${google_service_account.gcr_cleaner.account_id}]",
  ]
}
````

K8s yaml:
````
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: gcr-cleaner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gcr-cleaner
    app.kubernetes.io/version: 0.5.0
    helm.sh/chart: gcr-cleaner-0.1.5
  name: gcr-cleaner
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcr-cleaner-prod
  labels:
    helm.sh/chart: gcr-cleaner-0.1.4
    app.kubernetes.io/name: gcr-cleaner
    app.kubernetes.io/instance: gcr-cleaner
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: 18 16 * * *
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1      
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: gcr-cleaner
        app.kubernetes.io/instance: gcr-cleaner
    spec:
      template:
        spec:
          serviceAccountName: gcr-cleaner
          containers:
            - name: gcr-cleaner
              image: "europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest"
              imagePullPolicy: IfNotPresent
              args:
                - -repo
                - "europe-west1-docker.pkg.dev/project-id/container-registry"
                - -recursive
                - -allow-tagged
                - -tag-filter
                - "^v?(\\d+\\.?){3}-\\d+$"
                - -keep
                - "3"
                - -grace
                - "24h"
              env:
                - name: GCRCLEANER_TOKEN
                  value: "hard coded token get by  gcloud auth print-access-token"                
          restartPolicy: Never
````

Is there any chance to run gcr-cleaner-cli in this way ? I'm already using this strategy with node and python applications to authenticate them to other google services like Cloud Trace and Cloud Storage and it's work fine. At the moment to run a cleanup one time per week i'm updating the env var GCRCLEANER_TOKEN with an hard coded token ... but is a really dirty job 😭  

Have a nice day 😃

**Comment by sethvargo** [comment]
Can you confirm that WI is configured correctly on the pod by replacing the container with `gcloud` and running `gcloud auth list` and `gcloud info`?

**Comment by xpicio** [comment]
gcloud auth list
```
            Credentialed Accounts
ACTIVE  ACCOUNT
*       scm-maestroconnect-shared.svc.id.goog

To set the active account, run:
    $ gcloud config set account `ACCOUNT`
```

gcloud info
```
Google Cloud SDK [359.0.0]

Platform: [Linux, x86_64] uname_result(system='Linux', node='gcr-cleaner-demo-manual-vjdd8-zw6c2', release='5.4.129+', version='#1 SMP Thu Jul 8 19:57:33 PDT 2021', machine='x86_64', processor='')
Locale: ('en_US', 'UTF-8')
Python Version: [3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]]
Python Location: [/usr/bin/python3]
Site Packages: [Disabled]

Installation Root: [/usr/lib/google-cloud-sdk]
Installed Components:
  alpha: [2021.09.24]
  cloud-firestore-emulator: [1.13.0]
  kpt: [1.0.0-beta.5]
  bigtable: []
  app-engine-python-extras: [1.9.94]
  bq: [2.0.71]
  pubsub-emulator: [0.5.0]
  beta: [2021.09.24]
  cloud-datastore-emulator: [2.1.0]
  cloud-spanner-emulator: [1.3.0]
  datalab: [20190610]
  core: [2021.09.24]
  app-engine-go: [1.9.71]
  app-engine-java: [1.9.91]
  cbt: [0.10.1]
  gsutil: [5.2]
  app-engine-python: [1.9.94]
  local-extract: [1.3.1]
System PATH: [/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/google-cloud-sdk/bin/]
Python PATH: [/usr/bin/../lib/google-cloud-sdk/lib/third_party:/usr/lib/google-cloud-sdk/lib:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload]
Cloud SDK on PATH: [False]
Kubectl on PATH: [/usr/bin/kubectl]

Installation Properties: [/usr/lib/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/root/.config/gcloud/configurations/config_default]

Account: [scm-maestroconnect-shared.svc.id.goog]
Project: [scm-maestroconnect-shared]

Current Properties:
  [core]
    account: [scm-maestroconnect-shared.svc.id.goog]
    disable_usage_reporting: [True]
    project: [scm-maestroconnect-shared]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2021.09.28/16.15.31.255504.log]

git: [git version 2.20.1]
ssh: [OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019]

```

**Comment by sethvargo** [comment]
Hmm okay so it's definitely getting the correct service account... I may need to add the special dance to support WIF.

**Comment by sethvargo** [comment]
I updated to the latest client libraries and confirmed this is working now.

**Comment by mrvarmazyar** [comment]
Hello everyone, 

I'm trying to deploy the GCR cleaner CLI using Kubernetes cronjob. I created the service account with the required IAM bindings but I still have the permission problem here, because I didn't declare this part of the deployment:
```YAML
              env:
                - name: GCRCLEANER_TOKEN
                  value: "hard coded token get by  gcloud auth print-access-token"
```
So my question is how I can set this environment variable automatically?
Can I export a key on the service account and then put that to the secret manager and use that secret as a value of this environment variable?

**Comment by xpicio** [comment]
Hello, if your service account binding (the service account created in the cluster with the service account created on GCP) you don't need to use the env variable `GCRCLEANER_TOKEN`.

**Comment by mrvarmazyar** [comment]
@xpicio Thanks for your quick response!
So I think something is wrong on my terraform and kubernetes declarations:
my terraform:
```tf
resource "google_service_account" "ar_cleaner" {
  account_id   = "ar-cleaner"
  display_name = "Artifact Registry Cleaner Account"
}

resource "google_artifact_registry_repository_iam_binding" "artifact_registry_admin" {
  provider = google-beta

  depends_on = [
    google_service_account.ar_cleaner
  ]

  project    = "My project name that includes AR"
  repository = "my-repo-name in the AR"
  location   = "us-east1"

  role = "roles/artifactregistry.repoAdmin"

  members = [
    "serviceAccount:${google_service_account.ar_cleaner.email}"
  ]
}

resource "google_service_account_iam_binding" "service_account_workload_indentity" {
  depends_on = [
    google_service_account.ar_cleaner
  ]

  service_account_id = google_service_account.ar_cleaner.name
  role               = "roles/iam.workloadIdentityUser"

  members = [
    "serviceAccount:${local.project_id}.svc.id.goog[default/${google_service_account.ar_cleaner.account_id}]",
  ]
}
```
my k8s job:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ar-cleaner
  name: ar-cleaner
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ar-cleaner-prod
spec:
  schedule: 40 14 * * *
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: ar-cleaner
        app.kubernetes.io/instance: ar-cleaner
    spec:
      template:
        spec:
          serviceAccountName: ar-cleaner
          containers:
            - name: ar-cleaner
              image: "us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli"
              imagePullPolicy: IfNotPresent
              args:
                - -repo
                - "My Repo Address"
                - -grace
                - "1920h"
          restartPolicy: Never

```

Is there any problem with these configurations?
